//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Game/General/Config/InputAction/GunInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GunInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GunInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GunInputActions"",
    ""maps"": [
        {
            ""name"": ""GunControls"",
            ""id"": ""11d8ea55-17fc-4f47-bd03-c2fc0c3374fd"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Value"",
                    ""id"": ""1a8f7857-ab94-457a-9c8f-18852fcf9d1e"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""f23f7ea5-d674-4507-be23-bfaf63992a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""97798ea7-2de9-407b-8900-136dacf57532"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""176fda60-dba1-4cd3-903c-88f5c2f613b8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f37c2451-9779-411e-82d7-77ad318200d5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9084add-4332-4db0-8530-680471431953"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GunSwitchingControls"",
            ""id"": ""ce03f94f-59fc-4b1d-8685-64bf705c6e67"",
            ""actions"": [
                {
                    ""name"": ""PrimaryWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""398224ad-c06b-41d3-8805-3de0998fde11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""28131743-1f00-41de-908b-7851f542bf04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollSwitching"",
                    ""type"": ""Value"",
                    ""id"": ""bd14187c-6475-417b-8353-0158e7c4c5f1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""54867aee-1366-4658-93d3-e8e8137d4402"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f549e440-f12c-4656-ac55-06be6a1f17ba"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4154f3f3-aed4-4323-953f-6e5ab6a4d2b6"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollSwitching"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GunControls
        m_GunControls = asset.FindActionMap("GunControls", throwIfNotFound: true);
        m_GunControls_Shoot = m_GunControls.FindAction("Shoot", throwIfNotFound: true);
        m_GunControls_Aim = m_GunControls.FindAction("Aim", throwIfNotFound: true);
        m_GunControls_Reload = m_GunControls.FindAction("Reload", throwIfNotFound: true);
        // GunSwitchingControls
        m_GunSwitchingControls = asset.FindActionMap("GunSwitchingControls", throwIfNotFound: true);
        m_GunSwitchingControls_PrimaryWeapon = m_GunSwitchingControls.FindAction("PrimaryWeapon", throwIfNotFound: true);
        m_GunSwitchingControls_SecondaryWeapon = m_GunSwitchingControls.FindAction("SecondaryWeapon", throwIfNotFound: true);
        m_GunSwitchingControls_ScrollSwitching = m_GunSwitchingControls.FindAction("ScrollSwitching", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GunControls
    private readonly InputActionMap m_GunControls;
    private IGunControlsActions m_GunControlsActionsCallbackInterface;
    private readonly InputAction m_GunControls_Shoot;
    private readonly InputAction m_GunControls_Aim;
    private readonly InputAction m_GunControls_Reload;
    public struct GunControlsActions
    {
        private @GunInputActions m_Wrapper;
        public GunControlsActions(@GunInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_GunControls_Shoot;
        public InputAction @Aim => m_Wrapper.m_GunControls_Aim;
        public InputAction @Reload => m_Wrapper.m_GunControls_Reload;
        public InputActionMap Get() { return m_Wrapper.m_GunControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GunControlsActions set) { return set.Get(); }
        public void SetCallbacks(IGunControlsActions instance)
        {
            if (m_Wrapper.m_GunControlsActionsCallbackInterface != null)
            {
                @Shoot.started -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnShoot;
                @Aim.started -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnAim;
                @Reload.started -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_GunControlsActionsCallbackInterface.OnReload;
            }
            m_Wrapper.m_GunControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
            }
        }
    }
    public GunControlsActions @GunControls => new GunControlsActions(this);

    // GunSwitchingControls
    private readonly InputActionMap m_GunSwitchingControls;
    private IGunSwitchingControlsActions m_GunSwitchingControlsActionsCallbackInterface;
    private readonly InputAction m_GunSwitchingControls_PrimaryWeapon;
    private readonly InputAction m_GunSwitchingControls_SecondaryWeapon;
    private readonly InputAction m_GunSwitchingControls_ScrollSwitching;
    public struct GunSwitchingControlsActions
    {
        private @GunInputActions m_Wrapper;
        public GunSwitchingControlsActions(@GunInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryWeapon => m_Wrapper.m_GunSwitchingControls_PrimaryWeapon;
        public InputAction @SecondaryWeapon => m_Wrapper.m_GunSwitchingControls_SecondaryWeapon;
        public InputAction @ScrollSwitching => m_Wrapper.m_GunSwitchingControls_ScrollSwitching;
        public InputActionMap Get() { return m_Wrapper.m_GunSwitchingControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GunSwitchingControlsActions set) { return set.Get(); }
        public void SetCallbacks(IGunSwitchingControlsActions instance)
        {
            if (m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface != null)
            {
                @PrimaryWeapon.started -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnPrimaryWeapon;
                @PrimaryWeapon.performed -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnPrimaryWeapon;
                @PrimaryWeapon.canceled -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnPrimaryWeapon;
                @SecondaryWeapon.started -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnSecondaryWeapon;
                @SecondaryWeapon.performed -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnSecondaryWeapon;
                @SecondaryWeapon.canceled -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnSecondaryWeapon;
                @ScrollSwitching.started -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnScrollSwitching;
                @ScrollSwitching.performed -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnScrollSwitching;
                @ScrollSwitching.canceled -= m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface.OnScrollSwitching;
            }
            m_Wrapper.m_GunSwitchingControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PrimaryWeapon.started += instance.OnPrimaryWeapon;
                @PrimaryWeapon.performed += instance.OnPrimaryWeapon;
                @PrimaryWeapon.canceled += instance.OnPrimaryWeapon;
                @SecondaryWeapon.started += instance.OnSecondaryWeapon;
                @SecondaryWeapon.performed += instance.OnSecondaryWeapon;
                @SecondaryWeapon.canceled += instance.OnSecondaryWeapon;
                @ScrollSwitching.started += instance.OnScrollSwitching;
                @ScrollSwitching.performed += instance.OnScrollSwitching;
                @ScrollSwitching.canceled += instance.OnScrollSwitching;
            }
        }
    }
    public GunSwitchingControlsActions @GunSwitchingControls => new GunSwitchingControlsActions(this);
    public interface IGunControlsActions
    {
        void OnShoot(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
    }
    public interface IGunSwitchingControlsActions
    {
        void OnPrimaryWeapon(InputAction.CallbackContext context);
        void OnSecondaryWeapon(InputAction.CallbackContext context);
        void OnScrollSwitching(InputAction.CallbackContext context);
    }
}
