using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class EnemyDataModel 
{
    [RealtimeProperty(1, true, true)]
    private int _enemyHP;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class EnemyDataModel : RealtimeModel {
    public int enemyHP {
        get {
            return _enemyHPProperty.value;
        }
        set {
            if (_enemyHPProperty.value == value) return;
            _enemyHPProperty.value = value;
            InvalidateReliableLength();
            FireEnemyHPDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(EnemyDataModel model, T value);
    public event PropertyChangedHandler<int> enemyHPDidChange;
    
    public enum PropertyID : uint {
        EnemyHP = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _enemyHPProperty;
    
    #endregion
    
    public EnemyDataModel() : base(null) {
        _enemyHPProperty = new ReliableProperty<int>(1, _enemyHP);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _enemyHPProperty.UnsubscribeCallback();
    }
    
    private void FireEnemyHPDidChange(int value) {
        try {
            enemyHPDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _enemyHPProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _enemyHPProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.EnemyHP: {
                    changed = _enemyHPProperty.Read(stream, context);
                    if (changed) FireEnemyHPDidChange(enemyHP);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _enemyHP = enemyHP;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
